version: '3.7'

services:
  redis:
    image: redis:latest
    container_name: redis
    restart: always
    ports:
      - 32768:6379  
    networks:
     - devnet

networks:
  devnet:
    external: true