version: '3.1'

services:
  db:
    image: postgres
    container_name: postgres
    restart: always
    env_file:
      - ../common.env
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.me.rule=Host(`me.sharon`)"
      - "traefik.http.routers.me.entrypoints=web"      
    ports:
      - 5432:5432
    networks:
      - devnet
         
  adminer:
    image: adminer
    container_name: adminer    
    restart: always
    ports:
      - 8080:8080
    networks:
      - devnet
          
networks:
  devnet:
    external: true

volumes:
  data:
  config:
