version: "3.7"
services:
  filebeat:
    image: docker.elastic.co/beats/filebeat:7.7.0
    user: root
    container_name: filebeat
    restart: always
    volumes:
    - ./filebeat.yml:/usr/share/filebeat/filebeat.yml:ro
    #- /var/lib/docker/containers:/var/lib/docker/containers:ro
    - /var/lib/docker/containers:/usr/share/dockerlogs/data:ro
    - /var/run/docker.sock:/var/run/docker.sock:ro
    command: filebeat -e -strict.perms=false
    ports:
    - 7000:80
    environment:
    - output.logstash.hosts=logstash:5044
    networks:
    - devnet
networks:
  devnet:
    external: true