version: "3"
services:
  filebeat:
    image: docker.elastic.co/beats/filebeat:7.7.0
    volumes:
    - ./filebeat.docker.yml:/usr/share/filebear/filebear.yml:ro
    - /var/lib/docker/containers:/var/lib/docker/containers:ro
    - /var/run/docker.sock:/var/run/docker.sock:ro
    command: filebeat
    ports:
    - 7000:80
    environment:
    - output.elasticsearch.hosts=192.168.1.96:9200
