version: '3'
services:
  nginx: 
    image: nginx:latest
    container_name: development_nginx
    restart:always
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 81:81

    
