version: '3'
services:
  kibana:
    image: docker.elastic.co/kibana/kibana:7.7.0
    volumes:
      - ./kibana.yml:/usr/share/kibana/config/kibana.yml
    environment:
      - ELASTICSEARCH_HOSTS=["http://192.168.1.96:9200"]
      - SERVER_HOST=0.0.0.0
    ports:
      - 5601:5601
