version: "3"
services:
  logstash:
    image: docker.elastic.co/logstash/logstash:7.7.0
    volumes:
    - ./:/config-dir
    command: logstash -f /config-dir/logstash.conf 
    ports:
    - 5044:5044
    - 9600:9600
    environment:
    - monitoring.elasticsearch.hosts=http://192.168.1.96:9200
    - xpack.monitoring.enabled=false
