version: '3'
services:
  registry:
    restart: always
    image: registry:2
    container-name: docker-registry
    ports:
    - "5000:5000"
    environment:
      REGISTRY_STORAGE_FILESYSTEM_ROOTDIRECTORY: /data
    volumes:
      - ~/data/docker-registry:/data
