version: "3.7"
services:
 rabbitmq1:
  restart: always
  hostname: rabbitmq1
  image: "rabbitmq:3-management"
  container_name: rabbitmq1
  ports:
    - "5672:5672"
    - "15672:15672"
  volumes: 
    - data:/var/lib/rabbitmq1
  environment:
    - RABBITMQ_ERLANG_COOKIE=cluster_cookie
  networks:
    - devnet

 rabbitmq2:
  restart: always
  hostname: rabbitmq2
  links:
   - rabbitmq1
  image: "rabbitmq:3-management"
  container_name: rabbitmq2
  ports:
   - "5673:5672"
   - "15673:15672"
  environment:
   - CLUSTERED=true    
   - CLUSTER_WITH=rabbitmq1    
   - RAM_NODE=true
   - RABBITMQ_ERLANG_COOKIE=cluster_cookie
  volumes:
   - data:/var/lib/rabbitmq2
networks:
  devnet:
    external: true

volumes:
  data:
