version: "3.7"
services:
 rabbitmq:
  restart: always
  hostname: "rabbit"
  image: "rabbitmq:3-management"
  container_name: rabbitmq
  ports:
    - "5672:5672"
    - "15672:15672"
  volumes:
    - "~/data/rabbitmq:/var/lib/rabbitmq/mnesia/"
  networks:
    - devnet
networks:
  devnet:
    external: true