version: "3.3"

services:

  traefik:
    image: "traefik"
    container_name: "traefik"
    command:
      - "--log.level=DEBUG"
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=true"
      - "--entrypoints.web.address=:90"
    ports:
      - "90:80"
      - "9090:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
    networks:
      - devnet

  whoami:
    image: "containous/whoami"
    container_name: "whoami"
    ports:
      - "80:80"    
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.whoami.rule=Host(`whoami.sharon`)"
      - "traefik.http.routers.whoami.entrypoints=web"
    networks:
      - devnet
  
networks:
  devnet:
    external: true